[target.aarch64-unknown-linux-gnu]
linker = ".cargo/aarch64-linux-gnu_zig"

[target.x86_64-unknown-linux-gnu]
linker = ".cargo/x86_64-linux-gnu_zig"

[target.x86_64-pc-windows-gnu]
linker = ".cargo/x86_64-windows-gnu_zig"
